### ISSUE TITLE
attribute 의 사용처에 대하여

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/Tteok#12]
저는 리슾의 keyword parameter 과 같은 용도로 사용하면 좋을 거 같다고 생각합니다

**Comment by seeeturtle** [comment]
이거 제가 계속 얘기했던 건데요....
python의 keyword parameter

**Comment by ENvironmentSet** [comment]
Common lisp의 keyword param이용..

**Comment by seeeturtle** [comment]
네네 거의 똑같아요.

차이점이라고는 단지 lisp는 확실하게 명시한다는거죠. python는 keyword argument를 dict로 넘겨줘요.

**Comment by seeeturtle** [comment]
@ENvironmentSet PR 날리시죠?

**Comment by ENvironmentSet** [comment]
@seeturtle
일요일 오후에 올리겠습니다.

**Comment by seeeturtle** [comment]
@EnvironmentSet ... 언제쯤 해주실 건가요

**Comment by ENvironmentSet** [comment]
다음주 일요일이용..

**Comment by seeeturtle** [comment]
attribute의 사용처가 두가지가 될 것 같습니다.
1. 함수 호출:
얘는 키워드 인자로서 하면 되지 않을 까 싶네요

2. 함수 선언:
두가지 경우가 있는데
a. 키워드 인자 선언
b. 인자의 기본값 선언

이걸 정해야 할 것 같습니다.

@ENvironmentSet
