### ISSUE TITLE
7/5 ~ 7/9 사이에 논의된 사항의 표준 문서 삽입건에 대하여

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/Tteok#14]
개인적인 대화에서도 몇 번 언급하였듯이, 그 당시 논의된 사항들도 떡 표준에 추가시킬 생각입니다. 이에 대해 어떻게 생각하시나요?

**Comment by seeeturtle** [comment]
네, 그렇게 하는게 괜찮을 것 같습니다. 다만 공모전이기에 만든 사항들은 제외시키는게 맞다거 생각합니다.

2018. 7. 22. 오후 10:07 Jaewon Seo <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
공모전이기에 만든 사항의 예를 들어주실 수 있으신가요?

**Comment by seeeturtle** [comment]
예로들면 1 0을 참 거짓을 생각하는게 있겠죠.

그리고 두가지 질문이 있습니다
1. 이전 문서에 있던 것들은 대부분은 predefined 함수 아닌가요?
2. 코드 객체는 계속 유지되는 건가요? (컨테이너라는 이름으로?)

2018. 7. 23. 오후 6:04 Jaewon Seo <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
1. 그 당시 정의된 함수들은 추가적인 검수를 거친 후 당락을 결정할 생각입니다.
2. 코드 객체의 개념은 유지하나, 구조/접근 방식 등은 **더 우아한** 방식으로의 전환을 꾀할 생각입니다.

**Comment by seeeturtle** [comment]
알겠습니다. 우아한 방식은 #15에서 논의해야겠죠

2018. 7. 24. 오후 1:54 Jaewon Seo <notifications@github.com> 작성:

**Comment by seeeturtle** [comment]
@ENvironmentSet 추가할 함수가 뭐가 있을지 작성해주실 수 있나요?

**Comment by ENvironmentSet** [comment]
@seeeturtle 언어 디자인을 마친 후에 논의하는게 더 좋지 않을까요?

**Comment by seeeturtle** [comment]
넵 알겠습니다. 그럼 이 이슈는 나중에 고려하도록 하죠

**Comment by ENvironmentSet** [comment]
이 기간 사이에 논의된 일들은 추가되는 게 확정된 것 인가요?

**Comment by seeeturtle** [comment]
우선은 논의 된 일들을 모두 나열해야할 것 같네요

2018. 7. 29. 오후 4:39 Jaewon Seo <notifications@github.com> 작성:
