### ISSUE TITLE
컨테이너의 내부적 구조 정의 및 다이아그램 수정

### ISSUE THREAD

**Issue by seeeturtle** [Tteoksal/Tteok#15]
1. 어떤 방식으로 구현될지(내부적으로 객체로 또는 또다른 타입)
2. 내부적인 구조는 어떻게 될지 (자세하게)

를 논의를 해야할 것 같습니다

**Comment by seeeturtle** [comment]
자 그럼 지금 결정된 것은
- head: container head의 값
- attribute: 속성-값 map
- body: 다른 element들의 리스트

를 속성으로 가지는 타입인거죠?

**Comment by ENvironmentSet** [comment]
#21 fixed by. #23  에서 언급했듯이 PR과 이슈의 연결 부탁드립니다.

**Comment by seeeturtle** [comment]
그 PR은 완벽하지 않습니다
