### ISSUE TITLE
boolean 타입과 값 정의

### ISSUE THREAD

**Issue by seeeturtle** [Tteoksal/Tteok#18]
1. boolean 타입의 정의는?
2. boolean 값은 무엇이 있는지?
를 정의해야할 것 같습니다.

**Comment by seeeturtle** [comment]
어제 얘기한 거는
boolean 타입을 없애고
nil을  거짓, 나머지는 참으로 취급하자였고

저는 그냥 true, false라는 상수를 만들 었으면 합니다

@ENvironmentSet 어떻게 생각하시나요?

**Comment by ENvironmentSet** [comment]
@seeeturtle 
nil을 거짓, 나머지를 참으로 취급하고.
전역 스코프에 true( = 1), false(= nil) 이라는 immutable binding 을 만드는 게 어떨까요?

**Comment by seeeturtle** [comment]
네.괜찮을 것 같습니다 :)

**Comment by seeeturtle** [comment]
Closed by #19
