### ISSUE TITLE
떡의 컨셉

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/Tteok#2]
떡의 컨셉으로 '시각적이며 간단하고, 명료한 프로그래밍 언어' 를 하려 하는데 여러분의 생각은 어떠신가요?
프로그래밍 패러다임으로는 멀티-패러다임을 채택할 생각입니다.
코드의 형식은 SGML이 시각적인 부분에서 강력하게 작용할 수 있기에  SGML의 형식을 따르려고 합니다.

**Comment by seeeturtle** [comment]
html-like language라는 컨셉은 버리시는 건가요?
버리시는 거면 저 컨셉도 나쁘지 않을 것 같습니다.
근데 시각적이라는기 무슨 의미인지는 잘 모르겠네요.

p.s. sgml은 메타 언어이므로 html-like 형식이라는게 좀 더 맞는 표현인 것 같습니다. 너무 진지충이였나요 :)

**Comment by seeeturtle** [comment]
@ENvironmentSet
html-like language라는 컨셉은 버리시는 건가요?
버리시는 거면 저 컨셉도 나쁘지 않을 것 같습니다.
근데 시각적이라는기 무슨 의미인지는 잘 모르겠네요.

p.s. sgml은 메타 언어이므로 html-like 형식이라는게 좀 더 맞는 표현인 것 같습니다. 너무 진지충이였나요 :)

**Comment by ENvironmentSet** [comment]
아녜요 ㅎㅎ 시각적이라는 말은 [S-Expression](https://ko.wikipedia.org/wiki/S-%ED%91%9C%ED%98%84%EC%8B%9D) 을 의미하는 말입니다.

**Comment by ENvironmentSet** [comment]
다만 HTML의 특성상 각진 모양의 심볼(<, >)이 사용되니 [M-Expression](https://en.wikipedia.org/wiki/M-expression) 도 괜찮을 거 같습니다.

**Comment by seeeturtle** [comment]
우선 저로서는 m-expression과 s-expression의 특징(?)을 좀 더 알아봐야겠지만, 시각적이다라는 것과 s-expression과는 잘 매치가 안되는 것 같아요. 차라리 이해하기 쉽게 lisp like, xml like 같은 걸 쓰는게 더 났지 않을 까 싶네요

2018. 5. 2. 오후 4:28 서재원 <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
동의합니다. xml이 lisp나 sgml 보다 유명하니 xml-like 이라 표현하는 게 더 나을 수 있을 거 같네요. 다른분들 생각은 어떠신지?

**Comment by seeeturtle** [comment]
개인적으로 느끼기에는 lisp-like가 좀 더 입에 붙는 것 같아요... (매우 비논리적인 이유이지만) 그리고 lisp에 관한 위키 글을 링크로 달면 괜찮지 않을까요?
아래에다가 `lisp가 뭐냐고요?`와 같이.

2018. 5. 2. 오후 5:03 서재원 <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
proposal 레포로 욺겼습니다. proposal 레포에 이슈를 재 작성해주시면 감사하겠습니다.
