### ISSUE TITLE
서문에 목표 제정

### ISSUE THREAD

**Issue by seeeturtle** [Tteoksal/Tteok#22]
이건 계속 얘기해왔으면서 한번도 정리해서 기록해본적이 없는 것 같아 이번 이슈로 확실히 기록하려고 합니다.

예전에 Tteoksal/Tteok 방에서 채팅해서 정리한 결과로 다음과 같았습니다.

*jwmsg0525*:
> 지금까지의 내용 정리
> 1. 프로그래머의 실수를 줄인다.
> 2. 코드의 줄 수를 줄인다
> 3. 코드의 가독성을 높인다
> 4. 일관적으로 작동하는 언어를 만들고
> 5. 가벼운환경에서 동작하며
> 6. 플렛폼에 제약을 받지 않는
> 그러한 언어

*seeeturtle*:
> 정리하면:
> * 사용자의 실수를 줄여주는 언어
> * 가독성이 좋은 언어
> * 간결한 언어
> * 좋은 성능을 가진 언어
> * 많은 기능을 가진 언어
> * ...

그외에도 여러번의 채팅을 통해 정한 목표(또는 철학)을 정리하면 다음과 같다고 생각합니다.
1. 간단하다
~2. 가볍다(이건 1번과 겹칠까요?)~
~3. 사용자의 실수를 줄여준다.~
4. 간결하다
~5. 성능이 좋다. (흐음 과연 달성할 수 있을지 의문이네요...)~
~6. OS 종속적이지 않다~
7. 일관적이다
8. 확장성이 있다

가 있겠네요.
우선은 지금까지의 대화 내용으로 보았을때에 Lisp와 달리 간단한 언어(수많은 함수들까지 고려할때에. 그리고 사용자가 문법을 확장할 수 있도록 함)을 지향하기로 했기 때문에 많은 기능을 가진 언어는 뺐습니다.

@ENvironmentSet 괜찮은가요? 더 고려해야할께 있을까요? 괜찮으면 그대로 PR 날리겠습니다.

**Comment by ENvironmentSet** [comment]
#23  closed by, 다음부터는 PR에 close할 이슈도 연결해주세요.
