### ISSUE TITLE
선언부와 실행부를 나누자는 의견

### ISSUE THREAD

**Issue by jwmsg0525** [Tteoksal/Tteok#3]
코드의 간결성과 시각적으로 이점을 남기기 위해
어느 하나의 구역에서 선언을 하기 위해서는 선언부에 선언을 하는것으로 하는게 어떨지 생각이 듭니다.

지역변수의 경우에도 하당하는 지역에서 선언부를 만들어 해당 선언부 내에 선언하는게 어떨지..

**Comment by ENvironmentSet** [comment]
대략적인 형태를 제시해주실 수 있으신가요?

**Comment by seeeturtle** [comment]
굳이 그럴 필요가 있을까요?
물론 실행하기 전에 선언하는 걸 강제할 수 있지만
사용자에게 맡기는 게 문제가 있을 것 같지는 않습니다.

**Comment by seeeturtle** [comment]
제가 생각하기에는 이런 그림을 생각하고 있는 것 같습니다.
```
<head>
<define>
... // foo에 값을 배정
</define>
<define>
... // bar 함수 정의
</define>
</head>

<body>
<cont>bar <cont>5</cont></cont> // bar 호출
<cont>print foo</cont>
</body>
```

**Comment by jwmsg0525** [comment]
<pre>
define 테그는 어디서는 사용 가능합니다.
그대신 선언은 무조건 define 테그 내에서 이뤄져야 합니다.

&lt;head&gt;
&lt;define&gt;
... // foo 선언
... // bar 선언
&lt;/define&gt;
&lt;/head&gt;
</pre>

**Comment by ENvironmentSet** [comment]
흐음.. 위 코드들을 보니 각자 생각하는 떡 언어의 형태가 다른 거 같네요. 이런 세부적인(runtime semantics)는 차후로 미루고 당장 해야 할 문법적인 요소(static semantics)부터 정의하는 게 어떨까요?

**Comment by seeeturtle** [comment]
네 동의합니다. 최소한 의사소통을 위해서라도 문법적인 요소는 필요하다고 생각합니다

2018. 5. 2. 오후 8:37 서재원 <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
proposal 레포로 욺겼습니다. proposal 레포에 이슈를 재 작성해주시면 감사하겠습니다.
