### ISSUE TITLE
식별자 정의

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/Tteok#4]
아래 EBNF를 참고해 주세요.
`alphabet ::= A-z`
`number ::= 0-9`
`specialChar ::= _ |  ?`
`identifierHead ::= specialChar | alphabet`
`identifierBody ::= alphabet | number | specialChar `
`identifier ::= identifierHead { identifierBody } `

**Comment by jwmsg0525** [comment]
접두기호 마다 특별한 의미가 따로 있는지 궁금합니다.
또한 식별자에서 네이밍 할때 영어와 숫자외에 다른 기호를 섞는 경우가 있는데... 가능한지..

있다면 설명 부탁드립니다.

**Comment by ENvironmentSet** [comment]
위에서 언급하였듯이 EBNF 표기법을 따라 표기하였습니다.

**Comment by seeeturtle** [comment]
`_`와 `$`를 identifier의 기호중 하나로 추가하신 이유는 뭔가요?

**Comment by jwmsg0525** [comment]
제가묻는게 접두기호 _ 와 $ 이야기 입니다

**Comment by ENvironmentSet** [comment]
관례적으로 많은 프로그래밍 언어들이 허용하고 있는 접두어라 추가하였습니다.

**Comment by seeeturtle** [comment]
흠... 굳이 필요가 있을지는 모르겠네요. 안 넣어도 괜찮지 않을까 싶네요.

그리고 lisp의 EBNF를 어느정도 차용하는 것도 괜찮을 것 같아요

**Comment by ENvironmentSet** [comment]
lisp의 EBNF라.. 참고용으로는 괜찮을 거 같네요

**Comment by ENvironmentSet** [comment]
이야기가 좀 다른 방향으로 샌 것 같은데.. 일단 identifier 의 ebnf는 위에 나온 대로 하겠습니다.

**Comment by ENvironmentSet** [comment]
gitter/proposal 방에서 나온 의견을 수용해 ?를 identifier가 될 수 있는 문자로 추가하였습니다
@seeeturtle 추가적인 이유를 작성해주시면 감사하겠습니다

**Comment by seeeturtle** [comment]
예를 들어 인자가 짝수인지 아닌지 확인하는 함수가 있다고 합시다.
보통 이런 함수의 이름은 `is_even`과 같이 이름을 짓습니다.
하지만 ?를 허용하게 된다면 `even?`과 이름을 축약할 수 있습니다.
